### ISSUE TITLE
Some errors show "line: 0, column: 0"

### ISSUE THREAD

**Issue by jyn514** [oli-obk/cargo_metadata#157] opened 2021-04-14 05:21 UTC
This is not very helpful and makes it hard to diagnose what went wrong.

```
thread 'web::test::can_view_source' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `name`", line: 0, column: 0)', src/test/fakes.rs:186:14
```

**Comment by morr0ne** [comment] 2022-07-01 09:07
Maybe some more details could help improve this kinds of errors? I think this is actually caused by serde_json and not directly by this crate so that might be a better place to open an issue.

I see that I'm a year to late but if this isn't relevant anymore it's probably best to close this issue.

**Closed** 2022-07-01 09:10 UTC
