### ISSUE TITLE
not all releases have a corresponding tag

### ISSUE THREAD

**Issue by jplatte** [oli-obk/cargo_metadata#184] opened 2022-06-23 08:35 UTC
… and it doesn't seem there's a changelog anywhere, for almost all of the versions. Though I think I'll manage to upgrade without it.

**Comment by oli-obk** [comment] 2022-06-23 08:40
Yea... Maintaining changelogs and tags and all requires some diligence on my part, and I'm not really using this crate anymore at all, just making sure that PRs get merged.

**Comment by jplatte** [comment] 2022-06-23 09:21
Well personally I just haven't contributed because I haven't encountered any bugs or missing functionality so far. I guess I can start watching the repo and going from there though (answering questions in issues / seeing whether I can reproduce or fix reported bugs).

**Comment by jyn514** [comment] 2022-06-25 15:27
I think I have access too - sorry I haven't been putting in much work. I think we can make this easier to maintain if we ask people to update the changelog themselves when they make a PR.

**Comment by morr0ne** [comment] 2022-06-30 22:05
A changelog is a good idea, perhaps it would also be worth adding a Contributing file so that people know to add changes to the file.

**Comment by morr0ne** [comment] 2022-06-30 22:07
I think a good starting point might be github recommended community standars https://github.com/oli-obk/cargo_metadata/community, considering the repo doesn't even have a description.

**Comment by morr0ne** [comment] 2022-06-30 22:41
I created a changelog file in #186 that keeps track of the unreleased changes and the version 0.15.0, I don't know whether or not adding changes for older version is worth it but it should be possible.

**Comment by morr0ne** [comment] 2022-07-01 09:20
> Well... If anyone wants to write changelogs, I can easily give them the appropriate access on this repo. Not sure how inviting maintainers works. I only ever gave powers to people that were already doing the maintenance via regular contribs. Doing a call for maintainers will likely get a few people interested, but I don't have high hopes for long term commitments.
> 
> I think unless someone with a higher desire for quality contribs here consistently, we're stuck with me doing just the technical work

I'd be more than willing to maintain this crate if the current maintainers are okay with it. I work with this crate very often and I'd love to put some effort in improving it. I can't guarantee a long term commitment but I guess that is the state of open source projects unless you tranfer it to someone big like @rust-lang, and even then someone must still be willing to maintain it.

**Comment by obi1kenobi** [comment] 2022-12-17 16:14
I'm also interested in using this crate for a couple of personal projects, and would be willing to put effort into improving the GitHub Actions workflows here to automate tagging and publishing, if that kind of contribution would be welcome and helpful.

I'm also the author of `cargo-semver-checks`, and I noticed that the semver-checking action was considered but eventually disabled due to [a failure in CI](https://github.com/oli-obk/cargo_metadata/actions/runs/3314092235/jobs/5472917306). I looked into it and [the underlying issue appears to be resolved](https://github.com/obi1kenobi/cargo_metadata/actions/runs/3718810956/jobs/6307258818), so it should be safe to re-enable it again if it would be of interest. I'd also love feedback on what needs to be improved, since it helps prioritize across the many suggestions we've received in the last few months!

**Comment by oli-obk** [comment] 2023-01-10 10:45
Yes, such help would be much appreciated!

**Comment by obi1kenobi** [comment] 2023-01-10 15:23
Great, I'll put something together in the next couple of days!

We're currently hard at work on v2 of the GitHub Action, which will take advantage of prebuilt binaries and other tricks to speed up the checking process. But it might not be ready for a bit longer, so I can add the slower v1 Action or hold off entirely, whichever you prefer.

**Comment by oli-obk** [comment] 2023-01-10 15:29
Either is fine with me, if one of them causes you extra work, do the other one ^^

**Comment by obi1kenobi** [comment] 2023-01-12 02:02
Here's what I came up with: https://github.com/oli-obk/cargo_metadata/pull/214

**Comment by obi1kenobi** [comment] 2023-01-12 15:19
With #214 now merged, future releases are guaranteed to have a tag and a GitHub release entry associated with them.

Do cargo / crates.io have a way to report the commit hash each version was published with? If so, I'd be happy to do the work of finding the hashes for all historical versions and producing a list of `git tag` commands for someone with push access to run on the repo.

**Comment by oli-obk** [comment] 2023-01-12 15:26
> Do cargo / crates.io have a way to report the commit hash each version was published with?

**Comment by obi1kenobi** [comment] 2023-01-12 18:03
I asked on the Rust zulip: https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/.E2.9C.94.20git.20ref.20corresponding.20to.20cargo.20publish

Here's the answer, in case it helps the next person that tries to search for this:
> if you download the crate file and unpack it, there is usually a .cargo_vcs_info.json file inside with a git.sha1 field
>
> Just FYI, that file may not always be there. For example, if it was not published inside a git repository, or --allow-dirty was used. Or was published with a much older version of cargo before that feature was added.

**Comment by oli-obk** [comment] 2023-01-31 11:32
I tried to use the publish action, but [it failed](https://github.com/oli-obk/cargo_metadata/actions/runs/4053497192/jobs/6974179569#step:7:36) due to not being logged into crates.io

I did add a secret for the crates.io token, I'd have expected a different error in case I messed that up, so not sure what's wrong

**Comment by obi1kenobi** [comment] 2023-01-31 14:55
Just confirming, when you added the crates.io token secret, was that in the UI where you triggered the workflow? Or did you add it as a repo secret? I don't have permissions to trigger the workflow or to look at secrets so I can't look up the answer by myself.

The publish step here is [identical to the one](https://github.com/obi1kenobi/cargo-semver-checks/blob/main/.github/workflows/release.yml#L37-L40) in `cargo-semver-checks`, so I doubt the problem is near there.

For `cargo-semver-checks`, the crates.io token is a repo secret, but the configuration is a bit different: the release workflow is triggered by another workflow [which passes the secret explicitly](https://github.com/obi1kenobi/cargo-semver-checks/blob/main/.github/workflows/ci.yml#L399-L403).

If back-and-forth over GitHub comments is too inefficient, I'm happy to hop on a quick call and help debug that way. GitHub Actions "YAML debugging" is sadly relatively common :(

**Comment by obi1kenobi** [comment] 2023-01-31 21:02
We sorted it out. It was a configuration issue in the GitHub secrets settings, where the crates.io token was the "wrong kind" of secret and was not accessible to the workflow. v0.15.3 is published and tagged successfully.

We can keep this issue open until I get a chance to track down and recover the missing tags for the prior versions.

**Comment by obi1kenobi** [comment] 2023-03-03 03:45
I finally had a bit of time to work on this: I plugged in the cargo index into [Trustfall](https://github.com/obi1kenobi/trustfall) and then ran the following query which fetched the gitrevs for each version, where they were available:
```graphql
{
    Crate(name: "cargo_metadata") {
        version {
            version @output
            is_yanked @output

            contents {
                cargo_vcs_info @optional {
                    gitrev @output
                    gitrev_kind @output
                    path_in_vcs @output
                }
            }
        }
    }
}
```

<details>
<summary>The query produced the following results:</summary>

```
[
  {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.1.0"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.1.1"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.1.2"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.2.0"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.2.1"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.2.3"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.3.0"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.3.1"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.3.2"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.3.3"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.4.0"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.4.1"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.5.1"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.5.2"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.5.3"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.5.4"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.5.5"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.5.6"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.5.7"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.5.8"
  }, {
    "gitrev": null,
    "gitrev_kind": null,
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.6.0"
  }, {
    "gitrev": "7678c74d76ac085c3ba255aa59dad6297a650cd4",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.6.1"
  }, {
    "gitrev": "111b5aa24b4cb2a2022f231400cc29d87b355284",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.6.2"
  }, {
    "gitrev": "f24b849c769cb58b24faa7ff17bfe8e2f8eb9d39",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.6.3"
  }, {
    "gitrev": "5e47d1d1b1ecbeae4fe5e2fa2f07762dff6aa64d",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.6.4"
  }, {
    "gitrev": "2681ef836629515fcc60268243fa1e06333a6960",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.7.0"
  }, {
    "gitrev": "dc24dd3dc7f017c270e64a79d1ff46dae3d3cf83",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.7.1"
  }, {
    "gitrev": "f93c1158c345b0ee947898f01cc5341b491647fd",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.7.2"
  }, {
    "gitrev": "a4f4d073e2c5c2941597c08192b41147c37cda33",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.7.3"
  }, {
    "gitrev": "9ad8aa93b1aace87e872c43aea0bb31eb7acdaab",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.7.4"
  }, {
    "gitrev": "2058bb6774273bf01df1b37e5adea319b47358ae",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.8.0"
  }, {
    "gitrev": "138c5da9c770a4124f7306611d3912e22cacdc22",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.8.1"
  }, {
    "gitrev": "b72eaa6475633fdc14f57316855200666e322771",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.8.2"
  }, {
    "gitrev": "b540f76635a023a100a5e354902c520657396ed0",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.9.0"
  }, {
    "gitrev": "b0402002af3009a6143d3fdc29d6d15dac4dcd3c",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.9.1"
  }, {
    "gitrev": "759d7ac201ab72b01d93329fe88dda0bbdc8966d",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.10.0"
  }, {
    "gitrev": "1882a5b64150ce61494bc14b8c5c9d00fe88a46a",
    "gitrev_kind": "sha1",
    "is_yanked": true,
    "path_in_vcs": null,
    "version": "0.10.1"
  }, {
    "gitrev": "70c474036b251c134ff101d161f8884e86795b4c",
    "gitrev_kind": "sha1",
    "is_yanked": true,
    "path_in_vcs": null,
    "version": "0.11.0"
  }, {
    "gitrev": "d36e795a22ba0a09af8c2175adb9323c2cc0c13c",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.11.1"
  }, {
    "gitrev": "3fa3b5ed148decb2cb9dc9fd0beaa5d346a82dc1",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.11.2"
  }, {
    "gitrev": "10effcd42cb146b4f7ae8b5a068289a2c9d02c50",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.11.3"
  }, {
    "gitrev": "625176c556e64d2be84e0f759937c325369c52ad",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.11.4"
  }, {
    "gitrev": "adbec0e32917c564564f66d1efb1cc66d1899290",
    "gitrev_kind": "sha1",
    "is_yanked": true,
    "path_in_vcs": null,
    "version": "0.11.5"
  }, {
    "gitrev": "c2af9589cb5d9cb5a7b54bb73e992ddb51efcf9b",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.12.0"
  }, {
    "gitrev": "4ffef9f31b9ab3bf275ecb42ea3d7c848cf7eb9f",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.12.1"
  }, {
    "gitrev": "48d94389b624f66816938d2f0313c56598f3a38d",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.12.2"
  }, {
    "gitrev": "bbd91e28d8fe2eba5ef57022d5cd536cbc6ff5a4",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.12.3"
  }, {
    "gitrev": "6b62bd0e3ed3d4c7e94c8c10e8fd5d8db992accd",
    "gitrev_kind": "sha1",
    "is_yanked": true,
    "path_in_vcs": null,
    "version": "0.13.0"
  }, {
    "gitrev": "540fc6cd8ea1624055c98faf92ef61f620b6aa8f",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.13.1"
  }, {
    "gitrev": "59c4c0181e046280632dd0c69159d65605ad8a80",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.14.0"
  }, {
    "gitrev": "06a5cf9156e1f64a42453b0dde314134274cffa0",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": null,
    "version": "0.14.1"
  }, {
    "gitrev": "f615f7164534eb52fb9525bdb5eee5731f652968",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": "",
    "version": "0.14.2"
  }, {
    "gitrev": "709d508c54593e4ee0ef00e94dd04a6158e6e5d7",
    "gitrev_kind": "sha1",
    "is_yanked": true,
    "path_in_vcs": "",
    "version": "0.14.3"
  }, {
    "gitrev": "c800efe4d658ba43b8d43385acbd55dcbd84636d",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": "",
    "version": "0.15.0"
  }, {
    "gitrev": "feac4afaa136f0bb7a7d2f9992e86d9a78f5d5af",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": "",
    "version": "0.15.1"
  }, {
    "gitrev": "8319bd683d02a6b977beccbc66a5730ee6b95de3",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": "",
    "version": "0.15.2"
  }, {
    "gitrev": "8a79fea0c1a421b2d64411c05cf7ec9b794fc4da",
    "gitrev_kind": "sha1",
    "is_yanked": false,
    "path_in_vcs": "",
    "version": "0.15.3"
  }
]
```
</details>

After comparing to the tags in the repo, the following set of commands should:
- add all missing tags that crates.io knows about
- make all tags use a consistent `vX.Y.Z` format (and #221 will fix that going forward)
```bash
git tag v0.6.1 7678c74d76ac085c3ba255aa59dad6297a650cd4 && \
git tag v0.6.2 111b5aa24b4cb2a2022f231400cc29d87b355284 && \
git tag v0.6.3 f24b849c769cb58b24faa7ff17bfe8e2f8eb9d39 && \
git tag v0.6.4 5e47d1d1b1ecbeae4fe5e2fa2f07762dff6aa64d && \
git tag v0.7.0 2681ef836629515fcc60268243fa1e06333a6960 && \
git tag v0.7.1 dc24dd3dc7f017c270e64a79d1ff46dae3d3cf83 && \
git tag v0.8.0 2058bb6774273bf01df1b37e5adea319b47358ae && \
git tag v0.9.0 b540f76635a023a100a5e354902c520657396ed0 && \
git tag v0.10.1 1882a5b64150ce61494bc14b8c5c9d00fe88a46a && \
git tag v0.11.0 70c474036b251c134ff101d161f8884e86795b4c && \
git tag v0.11.3 10effcd42cb146b4f7ae8b5a068289a2c9d02c50 && \
git tag v0.14.1 0.14.1 && \
git tag v0.14.2 0.14.2 && \
git tag v0.15.3 0.15.3
```

I didn't want to make and push these tags unilaterally. @oli-obk what do you think?

**Comment by oli-obk** [comment] 2023-03-03 07:14
Modulo deciding on whether to use a `v` prefix or not, please do push tags at your own discretion

**Comment by obi1kenobi** [comment] 2023-03-03 15:22
I think we should use a `v` prefix on the tags between `v0.6` and `v0.11.3`, to match the surrounding tags. The style switch happens first at `0.14.1` for two tags, and then again at `0.15.3` which is the latest version. I think it could be annoying to users if we made more style switchovers in the tag format than already exist.

<details>
<summary>Here's where the new tags would fit into the existing ones:</summary>

```
v0.3
v0.6
v0.6.1 -> NEW
v0.6.2 -> NEW
v0.6.3 -> NEW
v0.6.4 -> NEW
v0.7
v0.7.0 -> NEW
v0.7.1 -> NEW
v0.7.2
v0.7.3
v0.7.4
v0.8
v0.8.0 -> NEW
v0.8.1
v0.8.2
v0.9.0 -> NEW
v0.9.1
v0.10.0
v0.10.1 -> NEW
v0.11.0 -> NEW
v0.11.1
v0.11.2
v0.11.3 -> NEW
v0.11.4
v0.11.5
v0.12.0
v0.12.1
v0.12.2
v0.12.3
v0.13.0
v0.13.1
v0.14.0
0.14.1
0.14.2
v0.14.3
v0.15.0
v0.15.1
v0.15.2
0.15.3
```
</details>

If you agree with the above, I'll make and push the following tags:
```bash
git tag v0.6.1 7678c74d76ac085c3ba255aa59dad6297a650cd4 && \
git tag v0.6.2 111b5aa24b4cb2a2022f231400cc29d87b355284 && \
git tag v0.6.3 f24b849c769cb58b24faa7ff17bfe8e2f8eb9d39 && \
git tag v0.6.4 5e47d1d1b1ecbeae4fe5e2fa2f07762dff6aa64d && \
git tag v0.7.0 2681ef836629515fcc60268243fa1e06333a6960 && \
git tag v0.7.1 dc24dd3dc7f017c270e64a79d1ff46dae3d3cf83 && \
git tag v0.8.0 2058bb6774273bf01df1b37e5adea319b47358ae && \
git tag v0.9.0 b540f76635a023a100a5e354902c520657396ed0 && \
git tag v0.10.1 1882a5b64150ce61494bc14b8c5c9d00fe88a46a && \
git tag v0.11.0 70c474036b251c134ff101d161f8884e86795b4c && \
git tag v0.11.3 10effcd42cb146b4f7ae8b5a068289a2c9d02c50
```

**Comment by obi1kenobi** [comment] 2023-03-03 17:00
Based on the conversation here https://github.com/oli-obk/cargo_metadata/pull/221#issuecomment-1453743488 I'm going to replace all the `v`-prefixed version tags with ones that have only the version number without a prefix: `1.2.3`.

I'll also add the new tags in the prefix-less format to match.

I plan to do this on Monday, no earlier than 72h from now, in case anyone has any concerns they'd like to raise.

**Comment by obi1kenobi** [comment] 2023-03-06 20:51
I have added all the new prefix-less tags to the repo.

<details>
<summary>Command I ran</summary>

```
git tag 0.3.0 v0.3 && \
git tag 0.6.0 v0.6 && \
git tag 0.6.1 7678c74d76ac085c3ba255aa59dad6297a650cd4 && \
git tag 0.6.2 111b5aa24b4cb2a2022f231400cc29d87b355284 && \
git tag 0.6.3 f24b849c769cb58b24faa7ff17bfe8e2f8eb9d39 && \
git tag 0.6.4 5e47d1d1b1ecbeae4fe5e2fa2f07762dff6aa64d && \
git tag 0.7.0 v0.7 && \
git tag 0.7.1 dc24dd3dc7f017c270e64a79d1ff46dae3d3cf83 && \
git tag 0.7.2 v0.7.2 && \
git tag 0.7.3 v0.7.3 && \
git tag 0.7.4 v0.7.4 && \
git tag 0.8.0 v0.8 && \
git tag 0.8.1 v0.8.1 && \
git tag 0.8.2 v0.8.2 && \
git tag 0.9.0 b540f76635a023a100a5e354902c520657396ed0 && \
git tag 0.9.1 v0.9.1 && \
git tag 0.10.0 v0.10.0 && \
git tag 0.10.1 1882a5b64150ce61494bc14b8c5c9d00fe88a46a && \
git tag 0.11.0 70c474036b251c134ff101d161f8884e86795b4c && \
git tag 0.11.1 v0.11.1 && \
git tag 0.11.2 v0.11.2 && \
git tag 0.11.3 10effcd42cb146b4f7ae8b5a068289a2c9d02c50 && \
git tag 0.11.4 v0.11.4 && \
git tag 0.11.5 v0.11.5 && \
git tag 0.12.0 v0.12.0 && \
git tag 0.12.1 v0.12.1 && \
git tag 0.12.2 v0.12.2 && \
git tag 0.12.3 v0.12.3 && \
git tag 0.13.0 v0.13.0 && \
git tag 0.13.1 v0.13.1 && \
git tag 0.14.0 v0.14.0 && \
git tag 0.14.3 v0.14.3 && \
git tag 0.15.0 v0.15.0 && \
git tag 0.15.1 v0.15.1 && \
git tag 0.15.2 v0.15.2 && \
git push upstream 0.3.0 && \
git push upstream 0.6.0 && \
git push upstream 0.6.1 && \
git push upstream 0.6.2 && \
git push upstream 0.6.3 && \
git push upstream 0.6.4 && \
git push upstream 0.7.0 && \
git push upstream 0.7.1 && \
git push upstream 0.7.2 && \
git push upstream 0.7.3 && \
git push upstream 0.7.4 && \
git push upstream 0.8.0 && \
git push upstream 0.8.1 && \
git push upstream 0.8.2 && \
git push upstream 0.9.0 && \
git push upstream 0.9.1 && \
git push upstream 0.10.0 && \
git push upstream 0.10.1 && \
git push upstream 0.11.0 && \
git push upstream 0.11.1 && \
git push upstream 0.11.2 && \
git push upstream 0.11.3 && \
git push upstream 0.11.4 && \
git push upstream 0.11.5 && \
git push upstream 0.12.0 && \
git push upstream 0.12.1 && \
git push upstream 0.12.2 && \
git push upstream 0.12.3 && \
git push upstream 0.13.0 && \
git push upstream 0.13.1 && \
git push upstream 0.14.0 && \
git push upstream 0.14.3 && \
git push upstream 0.15.0 && \
git push upstream 0.15.1 && \
git push upstream 0.15.2
```
</details>

I plan to delete the old `v`-prefixed tags tomorrow, in approximately 16h (and 96h from the datetime of the previous post).

<details>
<summary>Command I will run</summary>

```
git tag -d v0.3 && git push upstream v0.3 --delete \
git tag -d v0.6 && git push upstream v0.6 --delete \
git tag -d v0.7 && git push upstream v0.7 --delete \
git tag -d v0.7.2 && git push upstream v0.7.2 --delete \
git tag -d v0.7.3 && git push upstream v0.7.3 --delete \
git tag -d v0.7.4 && git push upstream v0.7.4 --delete \
git tag -d v0.8 && git push upstream v0.8 --delete \
git tag -d v0.8.1 && git push upstream v0.8.1 --delete \
git tag -d v0.8.2 && git push upstream v0.8.2 --delete \
git tag -d v0.9.1 && git push upstream v0.9.1 --delete \
git tag -d v0.10.0 && git push upstream v0.10.0 --delete \
git tag -d v0.11.1 && git push upstream v0.11.1 --delete \
git tag -d v0.11.2 && git push upstream v0.11.2 --delete \
git tag -d v0.11.4 && git push upstream v0.11.4 --delete \
git tag -d v0.11.5 && git push upstream v0.11.5 --delete \
git tag -d v0.12.0 && git push upstream v0.12.0 --delete \
git tag -d v0.12.1 && git push upstream v0.12.1 --delete \
git tag -d v0.12.2 && git push upstream v0.12.2 --delete \
git tag -d v0.12.3 && git push upstream v0.12.3 --delete \
git tag -d v0.13.0 && git push upstream v0.13.0 --delete \
git tag -d v0.13.1 && git push upstream v0.13.1 --delete \
git tag -d v0.14.0 && git push upstream v0.14.0 --delete \
git tag -d v0.14.3 && git push upstream v0.14.3 --delete \
git tag -d v0.15.0 && git push upstream v0.15.0 --delete \
git tag -d v0.15.1 && git push upstream v0.15.1 --delete \
git tag -d v0.15.2 && git push upstream v0.15.2 --delete 
```
</details>

Please let me know if you have any concerns before then.

**Comment by obi1kenobi** [comment] 2023-03-07 18:02
This is now completed:
- All tags have the format `x.y.z`.
- All versions for which crates.io held git ref information now have tags.

Some versions are still missing tags, but AFAIK there's no way to easily and uniquely recover which exact commit they correspond to. Even attempting to match crate contents vs historical repo state can produce multiple matches that would be difficult to disambiguate.

I think we've reached the optimal cost vs benefit point here. If you agree, let's close this issue.

**Closed** 2023-03-07 19:07 UTC

**Comment by obi1kenobi** [comment] 2023-03-07 19:46
Happy I could help! It was a useful dogfooding exercise for Trustfall on my end :)

It's trivial to do for any other crate too, if there are any other candidates. It's just a one-line tweak to my Trustfall query.
